### ISSUE TITLE
Add support for the new options validator in Core 2.2

### ISSUE THREAD

**Issue by VictorioBerra** [FluentValidation/FluentValidation#969] opened 2018-12-07 19:08 UTC
### System Details
- Core 2.2
- Options Validators https://github.com/aspnet/Options/pull/266
- https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2#options-validation

### Issue Description
I would really like to be able to apply FluentValidation rules to the new options validators. I know this is a big feature request, but i thought it was a good idea and it might be nice to put it up for grabs.

**Comment by JeremySkinner** [comment] 2018-12-07 19:13
Hi, do you have some examples/details of exaxtly what you’d like to see?

**Comment by VictorioBerra** [comment] 2018-12-07 19:20
This is a great question, but i am hardly the expert. I think a good first pass would look like this:

```csharp
using FluentValidation;

public class MyOptionsValidator: AbstractOptionsValidator<MyOptions> {
  public MyOptionsValidator() {
    RuleFor(x => x.ApiLocation).NotEmpty();
    RuleFor(x => x.ApiToken).NotEmpty().WithMessage("Please specify an API token");
    RuleFor(x => x.RetryCount).NotEqual(0).When(x => x.UsePolly);
    RuleFor(x => x.ApiVersion).Length(20, 250);
    RuleFor(x => x.SwaggerDocument).Must(BeAValidSwaggerDocument).WithMessage("Please specify a valid Swagger JSON Document");
  }

  private bool BeAValidSwaggerDocument(string postcode) {
    // custom Swagger JSON Document validating logic goes here
  }
}

// Registration
services.AddOptions<MyOptions>("optionalOptionsName")
    .Configure(o => { }) // Configure the options
    .Validate<MyOptionsValidator>();

// Consumption
var monitor = services.BuildServiceProvider()
    .GetService<IOptionsMonitor<MyOptions>>();

try
{
    var options = monitor.Get("optionalOptionsName");
}
catch (OptionsValidationException e) 
{
   // e.OptionsName returns "optionalOptionsName"
   // e.OptionsType returns typeof(MyOptions)
   // e.Failures returns a list of errors, which may contain 
   //     "Please specify a valid Swagger JSON Document"
}
```

**Comment by JeremySkinner** [comment] 2018-12-08 11:21
That seems reasonable. I'll put this on the backlog for now as it'd probably be a while before I'd get to it but I'd definitely like to see this in a future version.

**Comment by JeremySkinner** [comment] 2018-12-19 09:47
I did some research on this yesterday. This is going to be difficult to support for now as FluentValidation.AspNetCore targets 2.1 as the lowest supported version, and there isn't a good way to multi-target between different versions of 2.x without having a separate package (which I'm not particularly keen on introducing)

However, with .NET Core 3.0 coming, this will change as the ASP.NET Core version will be tied to the target framework, so we'll be able to support this from 3.0 onwards within the same package.

**Comment by VictorioBerra** [comment] 2018-12-19 14:40
Sounds great, 3.0 is not too far out either.

**Comment by iron9light** [comment] 2020-03-14 20:37
Any update? dotnet core 3.1 has been release for a while.

**Comment by JeremySkinner** [comment] 2020-03-14 20:40
@iron9light FluentValidation is fully supported on .net core 3.1, please see the documentation at http://docs.fluentvalidation.net

If you’re referring to the Options validation feature that was suggested then this hasn’t been built yet - the issue is marked as up for grabs and is awaiting someone to contribute the functionality.

**Comment by iron9light** [comment] 2020-03-14 20:56
I think this feature is for Microsoft.Extensions.Options, which is not a park of ASP.NET Core SDK. It will be good if there's another project, like "FluentValidation.Extensions.Options". @JeremySkinner What do you think?

**Comment by JeremySkinner** [comment] 2020-03-14 20:59
Possibly, but I’m not particularly keen on adding another package to the core as it increases the maintenance overhead. Maybe better as a separately maintained community package.

**Comment by iron9light** [comment] 2020-03-14 21:03
Got it. I will try to build this project when I have time. And will let you know when it's done. Wish it will be contributed to this repo one day.

**Comment by JeremySkinner** [comment] 2020-03-14 21:04
Ok sounds good, let me know if there’s any info you need.

**Comment by iron9light** [comment] 2020-03-15 14:39
Just built one :-) https://github.com/iron9light/FluentValidation.Extensions
And you can get the nightly build package here: https://github.com/iron9light/FluentValidation.Extensions/packages/153048
@JeremySkinner suggestions and feedbacks are welcome.

**Comment by JeremySkinner** [comment] 2020-03-16 09:10
@iron9light thanks for this. I haven't had a chance to look at it fully but one thing to note is that if you're planning on maintaining a nuget package for this you'll need to use a different prefix (the "FluentValidation" prefix is reserved). The usual convention is to use something like YourCompanyName.FluentValidation.Whatever

**Comment by iron9light** [comment] 2020-03-16 09:19
Got it.

**Comment by JeremySkinner** [comment] 2020-03-16 09:29
I'll try and have a play with it at some point soon (might not be this week), and if all looks good then I'll link to it from our documentation site

**Comment by iron9light** [comment] 2020-03-16 10:44
Prefix has been added.

**Comment by VictorioBerra** [comment] 2020-03-16 13:46
@iron9light Thanks for bringing my idea to life! :) should I close the issue now?

**Comment by aaronuurman** [comment] 2020-04-16 10:56
Hi!
It's a great idea, when can we see this in stable version?

**Comment by JeremySkinner** [comment] 2020-04-16 11:09
@aaronuurman this is maintained externally to the core fluentvalidation packages. Please open issues on the project repository at https://github.com/iron9light/FluentValidation.Extensions

**Closed** 2020-04-16 11:10 UTC
Labels: Help Wanted, Up-for-grabs

**Comment by aaronuurman** [comment] 2020-04-17 10:22
Thank you @JeremySkinner!
