### ISSUE TITLE
LanguageManager Translations Not Working in 10.1.0

### ISSUE THREAD

**Issue by ga15859** [FluentValidation/FluentValidation#1728] opened 2021-05-04 17:19 UTC
### FluentValidation version

10.1.0

### Summary

I have been using these lines without issue:

            AddTranslation("en", nameof(NotNullValidator), "'{PropertyName}' is required.");
            AddTranslation("en", nameof(NotEmptyValidator), "'{PropertyName}' is required.");

After upgrading to 10.1.0, the above lines no longer compile due to the change to generics.  I switched to just using the string name (e.g., "NotNullValidator"), but error messages now use the default "{PropertyName} must not be empty" for both NotNull and NotEmpty validations.  

I've tried several various combinations without success, even using nameof with a specific instance (e.g., nameof(NotNullValidator<String, ValidatableProperty<String>>) to see if I now needed to wire to specific types.  Debugger does show the code is still being called; I'm just assuming the AddTranslation never maps anymore as a result of the change to generics.  

Is there an easy fix?  The upgrade guide didn't mention anything that I saw.

**Comment by JeremySkinner** [comment] 2021-05-04 17:21
Hi, property validators became generic in 10.0 - you need to use strings for language keys instead:

```csharp
        AddTranslation("en", "NotNullValidator", "'{PropertyName}' is required.");
        AddTranslation("en", "NotEmptyValidator", "'{PropertyName}' is required.");
```

**Comment by ga15859** [comment] 2021-05-04 17:52
Hi there, I apologize, I was obviously not clear.  The first attempt I made to fix the issue is what you described (I switched to just using the string name), but it was still not using my updated strings.  It worked pre-upgrade, stopped working immediately after...

**Comment by JeremySkinner** [comment] 2021-05-04 17:54
Our tests for this functionality aren’t failing - please can you provide full steps to reproduce, ideally in the form of a unit test or a minimal sample project. Thanks.

**Comment by ga15859** [comment] 2021-05-04 17:57
Hi!  Unfortunately that's far from easy - it's a pretty big project, and ties FluentValidation and ReactiveUI together.  Let me see what I can do....

**Comment by ga15859** [comment] 2021-05-04 20:40
I switched from the Nuget to a downloaded copy of your source so I could step through the code, and found the issue.

When the call to FluentValidation.Resources.LanguageManager.GetString is called, the culture name is "en-US".  I had to explicitly add a translation for en-US in addition to en for the change to be seen:

            AddTranslation("en", "NotEmptyValidator","'{PropertyName}' is required.");
            AddTranslation("en-US", "NotEmptyValidator","'{PropertyName}' is required.");

Previously, I did not have to do this.  I'm using the same device / culture as before, so I am assuming that previously the "en" translation was picked up and used for an en-US culture request, but it is not now.

**Comment by JeremySkinner** [comment] 2021-05-04 20:57
Thanks for the update, and yes your assessment is correct. 

`en` is the fallback language, but if your culture is set to `en-US` then FluentValidation's `en-US` translations will be matched first, so you'd need to replace the `en-US` translation in the language manager for the change to show up, not just changing `en` (same also goes for `en-GB`. Other english locales will use `en`). 

Note that this behaviour wasn't introduced in 10.x, this has been the behaviour since 9.3.0 (although looking back  I don't think this was specifically documented in the release notes)

Anyway, it's working as intended so I'm going to go ahead and close this 
.

**Closed by JeremySkinner** 2021-05-04 20:57 UTC
Labels: Needs more information

**Comment by JeremySkinner** [comment] 2021-05-04 21:01
If you want to replace both the US & fallback translations (or the UK too) and want to save a bit of duplication you could put the values in a list and loop over them. Something like:

```csharp
var translations = new List<(string key, string message)> {
  ("NotEmptyValidator", "'{PropertyName}' is required"),
  ("NotEmptyValidator", "'{PropertyName}' is required"),
};
foreach (var translation in translations) {
  AddTranslation("en", translation.key, translation.message);
  AddTranslation("en-US", translation.key, translation.message);
}
```

**Comment by ga15859** [comment] 2021-05-04 21:23
Ahh, that makes sense, I upgraded from 9.2.2 to 10.1.  Regarding your comment about duplication, agreed, I implemented something very similar (sticking the languages into an array as well).  Thanks again!
