### ISSUE TITLE
Custom PropertyNameResolver not working as expected

### ISSUE THREAD

**Issue by oatsoda** [FluentValidation/FluentValidation#1399] opened 2020-05-22 14:26 UTC
FluentValidation.AspNetCore 8.6.2
Net Core 3.1

I am trying to add custom property name resolution to use camelCase and finding that it doesn't seem to be working correctly.

For example (I am using MediatR but am simplifying the setup/classes here for brevity)

Parameters
```
public class Query
{
   public string Email { get; set; }
}
```

Controller
`public async Task<IActionResult> GetList([FromQuery]Query query) {  ... }`

Validation Rules
```

public class QueryValidator : AbstractValidator<Query>
{
    public QueryValidator()
    {
        RuleFor(q => q.Email)
           .EmailAddress(); // Null is valid
    }
}
```

I've configured options to just do a very basic lowercasing of first letter:

```
ValidatorOptions.PropertyNameResolver = ResolvePropertyName;

private static string ResolvePropertyName(Type type, MemberInfo memberInfo, LambdaExpression expression)
{
	return DefaultPropertyNameResolver(type, memberInfo, expression)?
	   .LowercaseFirstLetter(); // Do we need to do full camelCase convertor?
}
        
// Taken from https://github.com/FluentValidation/FluentValidation/blob/26ae4b5d274eaff6952b4811de2aee0270604798/src/FluentValidation/ValidatorOptions.cs#L97
private static string DefaultPropertyNameResolver(Type type, MemberInfo memberInfo, LambdaExpression expression)
{
	if (expression != null)
	{
		var chain = PropertyChain.FromExpression(expression);
		if (chain.Count > 0) return chain.ToString();
	}

	if (memberInfo != null)
	{
		return memberInfo.Name;
	}

	return null;
}


public static class StringExtensions
{
	public static string LowercaseFirstLetter(this string value)
	{
		if (string.IsNullOrWhiteSpace(value) || char.IsLower(value, 0))
			return value;

		if (value.Length == 1)
			return value.ToLower();

		return char.ToLowerInvariant(value[0]) + value.Substring(1);
	}
}
```

However, if I call the API endpoint with `/?email=test` querystring I am getting this odd response:

>{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"One or more validation errors occurred.","status":400,"traceId":"00-65eeaaded4a920479a73be61b4da5778-ee7a0309a5564648-00","errors":{"Email":["'email' is not a valid email address."]}}

So you can see that it is strangely lowercasing the "display" values, but the property names are not.

I found [this issue](https://github.com/FluentValidation/FluentValidation/issues/1061) but not sure it is the same problem.

**Comment by JeremySkinner** [comment] 2020-05-22 17:26
Hi, where abouts are you setting `ValidatorOptions.PropertyNameResolver`? Just the once in application startup?

Also please could you put together a small runnable sample that reproduces the issue? Ideally a unit test but a small sample project would work too.

**Comment by JeremySkinner** [comment] 2020-05-22 17:28
Also: if you're able to reproduce it without the WebApi stuff involved (ie just by directly invoking the validator, no json serialization etc) that would help to track down where abouts the issue is occurring.

**Comment by oatsoda** [comment] 2020-06-01 08:34
@JeremySkinner Yes, just setting the validator once during startup.

'''
        public static void AddFluentValidation(this IServiceCollection services)
        {
            // Use Singletons for validators.
            services.AddValidatorsFromAssemblyContaining<Startup>(ServiceLifetime.Singleton);
            ValidatorOptions.PropertyNameResolver = ResolvePropertyName;
        }


       // In Startup.ConfigureServices()
       services.AddControllers()
                   .AddFluentValidation(); // IMvcBuilder extension
     
       services.AddFluentValidation(); // Call to custom extension method above
'''

I've just tried creating a very basic Non-ASP/WebApi unit test and the issue doesn't occur (just newing up the AbstractValidator<T> and calling Validate) so looks like it is with the web stuff.  I'll try and create a test project or integration test for that now.

**Comment by oatsoda** [comment] 2020-06-01 10:12
@JeremySkinner Attached is the simplest WebApi project with an integration test.

My gut feeling is that this is going to be related to the model binding and possibly similar to the issue I linked in my original post.

[FluentValidationWeb.zip](https://github.com/FluentValidation/FluentValidation/files/4710699/FluentValidationWeb.zip)

**Comment by JeremySkinner** [comment] 2020-06-01 10:52
Thanks for the sample project, that helps.

# First issue: Display name is lower cased
So the reason that the display name comes back as "email" rather than "Email" is because of the fallback behaviour. The display name resolution process looks like this:
- Is there a custom display name specific (with `WithName`)? 
- If not, is there a custom display name resolver? If so, use this.
- If not, take the actual property name (generated with the property name resolver) and do pascal-case split

So in your case, because you have a property name resolver that converts "Email" -> "email", "email" will be used both as the resulting property name, as well as the basis for generating the display name. Essentially by using a custom property name resolver you're completely replacing the string "Email" with "email" anywhere that FluentValidation would use to get the property name.  However in your case this isn't useful, as you want different casing for property name & display name. 

You can resolve this by explicitly setting a `ValidatorOptions.DisplayNameResolver` too that maintains the capitalization, eg:

```csharp
// SplitPascalCase is an extension method; needs FluentValidation.Internal namespace imported.
ValidatorOptions.DisplayNameResolver = (type, member, expr) => member.Name.SplitPascalCase();

```

# Second issue: Property name is not lowercased in the errors collection. 
I stepped through the code and FluentValidation is actually correctly generating a lowercased property name of "email". 

The issue is that ASP.NET core populates the ModelState dictionary before FluentValidation is executed with each exact property name on the model. In this case, ModelState is initialised with Key=Email, ValidationState=Unvalidated.

The dictionary that holds this is case-insensitive, so when the results from FluentValidation are copied into ModelState, they get merged with the existing entry (which is correct), but the existing key (with the uppercase "Email") will be preserved. 

This initialization of ModelState is outside of FluentValidation's control, so never runs through the property name resolver. 

I am not aware of any way of changing this, but I may be wrong - I think you'd need to do some investigation to see if there's a way of customizing the modelstate-generated property names. It's also possible that you might be able to use a filter that runs post-validation and rewrites the ModelState keys, although I haven't tried this to know if it's possible.

Hope that helps

**Comment by oatsoda** [comment] 2020-06-03 07:23
@JeremySkinner Thanks very much for the speedy reply to this.  I'm going to do some investigation on whether I can add something into the pipeline to detect 400 / Problem Details and change just before sending to the client.

**Closed** 2020-06-15 18:55 UTC
Labels: Needs more information
